### ISSUE TITLE
No effort feedback

### ISSUE THREAD

**Issue by samaypashine** [NiryoRobotics/ned_ros#13]
Hi, I'm trying to get effort feedback from the ned2 robot, but I'm not getting it. I'm running this commands:

**Terminal 1:**
`roslaunch niryo_robot_bringup niryo_ned2_robot.launch`

**Terminal 2:**
`rostopic echo /joint_states`

### Actual Behavior
Here's the output
![image](https://user-images.githubusercontent.com/51475380/228059649-e2e12110-5ab6-45ab-8f85-4dbc5b180208.png)

As you can see effort values are zeros. It's zero even if I move the arm.
I followed the instructions to use the ned2 arm on the website and it works as I'm able to control the arm using my script. I'm also using the latest version of ned_ros i.e. 4.1.0 but effort is not changing at all.

### Expected Behavior
Change in effort values in the image above.

**Also, I wanted to ask if there's any ros topic or any way that I can get information about force / torque when performing some motion with robot similar to UR5 /wrench or /gripper/joint_states.**

**Comment by ValentinPitre** [comment]
Hello, 
There is no force feedback and no force control  of joints neither on the Ned, nor on the Niryo One, nor on the Ned2. That's why the value is 0.

The only possible force control is on the control of the grippers. But I don't think we can read the force feedback of the gripper via ROS or an API. You have to read directly the registers of the Dynamixel.
